// src/components/Thanks.jsx
import { useEffect } from "react";

import Logo from "../media/Logo";

export default function Thanks({ setIsShowing }) {
  /* wait 2500, then unmount */
  useEffect(() => {
    setTimeout(function () {
      setIsShowing(-1);
    }, 2500);
  }, [setIsShowing]);

  return (
    <div className="flex justify-between space-x-5">
      <Logo className="h-6 w-6" />
      <h1>Gracias!</h1>
    </div>
  );
}

// src/components/Thanks.vue
<script setup>
import Logo from "../media/Logo.vue";
import { store } from "../store.js";
setTimeout(function () {
  store.currentTab = null;
}, 2500);
</script>

<template>
  <div class="flex justify-between space-x-5">
    <Logo class="h-6 w-6 m-auto" />
    <h1 class="">Gracias!</h1>
  </div>
</template>
