// src/media/Neutral.jsx
import * as React from "react"

const Neutral = (props) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 102.04 102.04"
    {...props}
  >
    <defs>
      <style>{".cls-2{fill:#231f20}"}</style>
    </defs>
    <g id="Capa_2" data-name="Capa 2">
      <g id="Capa_1-2" data-name="Capa 1">
        <circle
          cx={51.02}
          cy={51.02}
          r={48.02}
          style={{
            fill: "none",
            stroke: "#231f20",
            strokeMiterlimit: 10,
            strokeWidth: 6,
          }}
        />
        <circle className="cls-2" cx={38.29} cy={40.18} r={6.33} />
        <circle className="cls-2" cx={65.19} cy={40.18} r={6.33} />
        <path
          className="cls-2"
          d="M65.19 65.76H35.73c-3.22 0-3.22 5 0 5h29.46c3.22 0 3.22-5 0-5Z"
        />
      </g>
    </g>
  </svg>
)

export default Neutral

// src/media/Neutral.vue
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 102.04 102.04"
    :class="class"
  >
    <g id="Capa_2" data-name="Capa 2">
      <g id="Capa_1-2" data-name="Capa 1">
        <circle
          cx="51.02"
          cy="51.02"
          r="48.02"
          style="
            fill: none;
            stroke: rgb(35, 31, 32);
            stroke-miterlimit: 10;
            stroke-width: 6;
          "
        ></circle>
        <circle class="cls-2" cx="38.29" cy="40.18" r="6.33"></circle>
        <circle class="cls-2" cx="65.19" cy="40.18" r="6.33"></circle>
        <path
          class="cls-2"
          d="M65.19 65.76H35.73c-3.22 0-3.22 5 0 5h29.46c3.22 0 3.22-5 0-5Z"
        ></path>
      </g>
    </g>
  </svg>
</template>
